services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: nest-app-riskrice
        ports:
            - '3000:3000' # Map container's port 3000 to your machine
        depends_on:
            - db # Wait for the db service to be ready before starting the app
        volumes:
            - uploads_data:/app/uploads # Mount the local app directory to the container's /app directory
        env_file:
            - .env
    
    db:
        image: postgres:17.2 # Use PostgreSQL v17.2
        container_name: postgres-db-riskrice
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        ports:
            - '5434:5432' # Map container's port 5432 to your machine
        volumes:
            - postgres_data:/var/lib/postgresql/data # Persist database data
        env_file:
            - .env

volumes:
    postgres_data:
    uploads_data:
