services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: nest-app
        ports:
            - '3000:3000' # Map container's port 3000 to your machine
        depends_on:
            - db # Wait for the db service to be ready before starting the app
        volumes:
            - uploads_data:/app/uploads # Mount the local app directory to the container's /app directory

    db:
        image: postgres:17.2 # Use PostgreSQL v17.2
        container_name: postgres-db
        environment:
            POSTGRES_USER: riskrice
            POSTGRES_PASSWORD: memo
            POSTGRES_DB: axis
        ports:
            - '5434:5432' # Map container's port 5432 to your machine
        volumes:
            - postgres_data:/var/lib/postgresql/data # Persist database data

volumes:
    postgres_data:
    uploads_data:
